apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ep4sh-webserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo-webserver-helm-chart
    repoURL: https://github.com/ep4sh/demo-webserver
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true   
